### ISSUE TITLE
GRAPHC Needed, GRAPHX Provided

### ISSUE THREAD

**Issue by specialopsdave** [CE-Programming/libraries#30] opened 2017-09-09 02:45 UTC
When I attempt to play some games, I am told that I am missing a C library called GRAPHC, and it sends me here, where I can not find it. I already have the GRAPHX library installed though, and all the others provided from here.
![graphcerror](https://user-images.githubusercontent.com/31786008/30236437-754427e8-94d6-11e7-8b04-9f0b7b42f9d5.png)

**Comment by jacobly0** [comment] 2017-09-09 02:47
Duplicate of #28.

**Closed as completed by jacobly0** 2017-09-09 02:47 UTC
Labels: duplicate
