### ISSUE TITLE
[fileio lib] ti_OpenVar doesn't seem to work

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/libraries#4] opened 2016-02-20 02:36 UTC
@Snektron reported on #ez80-dev that `ti_Open("A", "w");` works but  `ti_OpenVar("A", "w", AppVar);` does not.
In fact, `ti_OpenVar` doesn't open programs either.

**Comment by mateoconlechuga** [comment] 2016-02-20 02:37
The issue is I counted from 1, not 0. Should be __frame_arg2, not __frame_arg3. Simple fix when I have a chance.

**Comment by mateoconlechuga** [comment] 2016-02-20 10:13
Merged Pull Requested and updated new release with tag 1.3. Thanks! :)

**Closed as completed by mateoconlechuga** 2016-02-20 10:13 UTC
Labels: bug
